[package]
name = "first_test"
version = "0.1.0"
edition = "2021"

[dependencies]

[lib]
name = "first_test"
#crate-type = ["cdylib"]      # Creates dynamic lib
crate-type = ["staticlib"] # Creates static lib

[target.x86_64-unknown-linux-musl]
linker = "rust-lld"
